### ISSUE TITLE
Issues with setup

### ISSUE THREAD

**Issue by JimSmith99** [norcino/docker-dotnet-core-api-qnap-nas#1]
Hi
You suggested that I should create an issue here, rather than continuing the conversation on the qnap forum. I have a couple of questions.

I have cloned the project and only made changes to build.ps1 file and nothing added in Container station.
I have made the following changes to the ps1 file:
$gatewayIpAddress = "192.168.1.1"
$subnet = "192.168.1.0/24"
$containerUrl = "tcp://192.168.1.144"

I have a shared folder Container (Qnap\DataVol1\Container) 
I have created a subfolder for the logs, so also this change to the ps1 file:
$logsVolumePath = "/Container/Logs"

I have not changed $containerIpAddress.
Not sure what to do with this one.

When I run the ps1 file I get: Build succeeded
When I try: http://192.168.1.144/api/values I get Not Found
And it it still empty in container station and there are no logs in the Logs folder.

Hope you can help

**Comment by norcino** [comment]
Hey Jim, you are missing the port for the containerUrl (that btw I might rename in dockerUrl).
try using tcp://192.168.1.144:2376.
Go to your NAS Web access, open container station app, go to Preferences, open the section Docker Certificate.
There you can find the port number (2376) and the certificate that you need to add to your local machine in order to be able to remotely connect to docker server.

EDIT: Yesterday I updated and finally QNAP released the update for the client (1.31) and the server (17.07.0), so I will be updating this guide soon, things will get much easier now

**Comment by JimSmith99** [comment]
Yes you are right, I forgot port number. Fixed!
I will wait for your update.

Meanwhile....
Do I need cert if I only use inside my home network?

**Comment by norcino** [comment]
Yes you do. The certificate is used for the authentication, has nothing to do with the SSL certificate used for the HTTPS connections.

To install the certificate on Windows:
1) Access *NAS Web page*
2) Open Container Station Application
3) On the left menu, go to *Preferences*
4) Open the section *Docker Certificate* on the top right
5) Click on the *Download* button to download a zip containing the needed certificates
6) Extract the content of the zip file in the folder *%USERPROFILE%/.docker*

**Comment by norcino** [comment]
I updated code base, script and guide.
I hope this will help.

**Comment by norcino** [comment]
I close the issue, the information provided and the source update should be enough.

**Comment by JimSmith99** [comment]
Hi

Yes, the information provided is enough....
I just got it up and running. This is awesome, thanks.
I have a couple of questions, hope you can help.

In what way do you setup a database?
Do you install it via container station, or do you use script for this aswell?

Can you point me in the right direction of how to setup local intranet hostname convention?
(Your example: nas.home will become 192.168.x.y (ip address of the nas.))

Br, Jim

**Comment by norcino** [comment]
Hi Jim, I'm happy this project helped you let's see if I can answer your questions.

1) If you want to use a relational database you can create the container directly from the Container Station UI. It is simple and because you don't need to change the image used to create the container, there is no point in setting up some kind of CI/CD.
Once created a container for a relational database, you will only access the database remotely via any tool you might want to use, and from there you will create or edit the content.
For NoSQL database you have an alternative, you can have the file stored in a folder if your application, that will be mapped to a shared folder in the NAS. You can see the example of the folder used for the log file. This is very important, do not ever store any data within a container, the containers are meant to be disposable and replaceable at any time.

2) For local hostname resolution, I use a router in which I run the custom ROM DDWRT.
DDWRT offers the option to specify a LAN domain, this for me is "home". Then in the DHCP reservation table, I can specify all the MAC and IP addresses plus the "hostname" I want to assign to each pair.
So when I setup a new entry, let's say for a new container that will host SQL Server database, I would add the "xx:xx:xx:xx:xx" / 192.168.0.111 / "sqlserver", to be able to reach the database using "sqlserver.home".
If you don't have DDWRT, you might want to check if your router supports this type of configuration.
If you are only interested in resolving containers name, you can use the hostname assigned to each container. For this approach check [https://docs.docker.com/engine/reference/commandline/create/](https://docs.docker.com/engine/reference/commandline/create/).

NOTE: if you want you can even run a dhcp server in a container but I don't recommend it. If you are interested in DDWRT, check this page: [https://www.dd-wrt.com/wiki/index.php/Supported_Devices](https://www.dd-wrt.com/wiki/index.php/Supported_Devices), maybe your router can be flashed with DDWRT ROM.
I use DDWRT for many other purposes, like Reverse Proxy, VPN Server and so on.
