### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by amasoumi** [norcino/docker-dotnet-core-api-qnap-nas#2]
hi there,
this is a great project, but the only thing i am actually confused about is the deployment from Visual Studio 2017, my question is where do i go for "docker network create", and how can i setup the publish in VS2017.
Thanks in advanced!

**Comment by norcino** [comment]
Hi, so there are 2 different scenarios:
1) Deployment for debugging, done using VS2017
2) Deployment for production, done using PowerShell script /Build/build.ps1

**Deployment for debugging**
You will start the debugging from VS2017, and it will automatically deploy the container in your local docker server and once completed you will be able to debug the application.
You don't need a custom network in this use case because that is needed only when running Docker on your NAS (QNAP Nas).

**Deployment for production**
When you want to deploy to your NAS a working version of your application, you will need to run the powershell script as described in the readme.md file.
This will created all the necessary docker items, including the network, storage and so on.

**Comment by amasoumi** [comment]
thanks for the explanation, and this is a great work you have done and shared online, i really like it, however i already figured out the powershell deployment, i was wondering if i can deploy it directly from VS2017, just like how we can deploy to Azure.
thanks, Alex

**Comment by norcino** [comment]
Thank you, I understand now.
I never tried, maybe there are plugins/extensions for VS, which allow you to set it as publishing option.

**Comment by amasoumi** [comment]
i will try to see if i can create a plugin for that, if i figure it out i will post it online and share it here as wwll, thanks again!
